packages:
    - better-themes
    - web
    - examples/*
allowBuilds:
    "@parcel/watcher": false
    esbuild: false
    sharp: false
minimumReleaseAgeExclude:
    - "@tanstack/react-start-rsc@0.1.30"
    - "@tanstack/react-start@1.168.31"
    - "@tanstack/start-plugin-core@1.171.23"
    - postcss@8.5.20
